import { LABEL_POSITION } from "./components/MetroLineMap";

const metroLineData: LineSegment[] = [
  {
    color: "#0692D2",
    line: 10,
    points: [
      { x: 140, y: 20, name: "HJULSTA", start: true },
      { x: 180, y: 50, name: "Tensta" },
      { x: 220, y: 80, name: "Rinkeby" },
      { x: 260, y: 110, name: "Rissne" },
      { x: 300, y: 140, name: "Duvbo" },
      { x: 340, y: 170, name: "Sundbybergs centrum" },
      { x: 380, y: 200, name: "Solna Strand" },
      { x: 530, y: 200, name: "Huvudsta" },
      { x: 680, y: 200, name: "Västra skogen" },
      { x: 680, y: 240, name: "Stadshagen" },
      {
        x: 680,
        y: 340,
        name: "Fridhemsplan",
        multi: true,
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 720, y: 380, name: "Rådhuset" },
      { x: 930, y: 380, name: "T-CENTRALEN", multi: true },
      { x: 1130, y: 380, name: "Kungsträdgården", end: true },
    ],
  },
  {
    color: "#0692D2",
    line: 11,
    points: [
      { x: 500, y: 20, name: "AKALLA", start: true },
      { x: 530, y: 50, name: "Husby" },
      { x: 560, y: 80, name: "Kista" },
      { x: 590, y: 110, name: "Hallonbergen" },
      { x: 620, y: 140, name: "Näckrosen" },
      { x: 650, y: 170, name: "Solna centrum" },
      { x: 680, y: 200, name: "Västra skogen" },
      { x: 680, y: 240, name: "Stadshagen" },
      {
        x: 680,
        y: 340,
        name: "Fridhemsplan",
        multi: true,
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 720, y: 380, name: "Rådhuset" },
      { x: 930, y: 380, name: "T-CENTRALEN", multi: true },
      { x: 1130, y: 380, name: "Kungsträdgården", end: true },
    ],
  },
  {
    color: "#20B159",
    line: 17,
    points: [
      {
        x: 420,
        y: 340,
        name: "ÅKESHOV",
        position: LABEL_POSITION.TOP,
      },
      {
        x: 460,
        y: 340,
        name: "Brommaplan",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 500,
        y: 340,
        name: "Abrahamsberg",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 540,
        y: 340,
        name: "Stora mossen",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 580,
        y: 340,
        name: "ALVIK",
        position: LABEL_POSITION.TOP,
      },
      {
        x: 620,
        y: 340,
        name: "Kristineberg",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 650,
        y: 340,
        name: "Thorildsplan",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 680,
        y: 340,
        name: "Fridhemsplan",
        multi: true,
        position: LABEL_POSITION.TOP_RIGHT,
      },
      {
        x: 720,
        y: 340,
        name: "St Eriksplan",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 760, y: 340, name: "Odenplan", position: LABEL_POSITION.TOP_RIGHT },
      {
        x: 800,
        y: 340,
        name: "Rädmansgatan",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 840, y: 340, name: "Hötorget", position: LABEL_POSITION.TOP_RIGHT },
      { x: 930, y: 380, name: "T-CENTRALEN", multi: true },
      { x: 930, y: 420, name: "Gamla stan", multi: true },
      { x: 930, y: 460, name: "Slussen", multi: true },
      { x: 930, y: 490, name: "Skanstull" },
      { x: 930, y: 520, name: "Gullmarsplan" },
      { x: 930, y: 550, name: "Skärmarbrink" },
      { x: 960, y: 570, name: "Hammarbyhöjden" },
      { x: 1000, y: 600, name: "Björkhagen" },
      { x: 1040, y: 630, name: "Kärrtorp" },
      { x: 1080, y: 660, name: "Bagarmossen" },
      { x: 1140, y: 700, name: "SKARPNÄCK", end: true },
    ],
  },
  {
    color: "#20B159",
    line: 18,
    points: [
      {
        x: 580,
        y: 340,
        name: "ALVIK",
        position: LABEL_POSITION.TOP,
      },
      {
        x: 620,
        y: 340,
        name: "Kristineberg",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 650,
        y: 340,
        name: "Thorildsplan",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 680,
        y: 340,
        name: "Fridhemsplan",
        multi: true,
        position: LABEL_POSITION.TOP_RIGHT,
      },
      {
        x: 720,
        y: 340,
        name: "St Eriksplan",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 760, y: 340, name: "Odenplan", position: LABEL_POSITION.TOP_RIGHT },
      {
        x: 800,
        y: 340,
        name: "Rådmansgatan",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 840, y: 340, name: "Hötorget", position: LABEL_POSITION.TOP_RIGHT },
      { x: 930, y: 380, name: "T-CENTRALEN", multi: true },
      { x: 930, y: 420, name: "Gamla stan", multi: true },
      { x: 930, y: 460, name: "Slussen", multi: true },
      { x: 930, y: 490, name: "Skanstull" },
      { x: 930, y: 520, name: "Gullmarsplan" },
      { x: 930, y: 550, name: "Skärmarbrink" },
      { x: 930, y: 620, name: "Blåsut" },
      { x: 930, y: 660, name: "Sandsborg" },
      { x: 930, y: 700, name: "Skogskyrkogården" },
      { x: 930, y: 750, name: "Tallkrogen" },
      { x: 930, y: 800, name: "Gubbängen" },
      { x: 930, y: 850, name: "Hökarängen" },
      { x: 930, y: 900, name: "Farsta" },
      { x: 930, y: 950, name: "FARSTA STRAND", end: true },
    ],
  },
  {
    color: "#20B159",
    line: 19,
    points: [
      {
        x: 80,
        y: 340,
        name: "HÄSSELBY STRAND",
        position: LABEL_POSITION.TOP,
        start: true,
      },
      {
        x: 140,
        y: 340,
        name: "Hässelby gård",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 180,
        y: 340,
        name: "Johannelund",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 220,
        y: 340,
        name: "Vällingby",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 260,
        y: 340,
        name: "Råcksta",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 300,
        y: 340,
        name: "Blackeberg",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 340,
        y: 340,
        name: "Islandstorget",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 380,
        y: 340,
        name: "Ängbyplan",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 420,
        y: 340,
        name: "ÅKESHOV",
        position: LABEL_POSITION.TOP,
      },
      {
        x: 460,
        y: 340,
        name: "Brommaplan",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 500,
        y: 340,
        name: "Abrahamsberg",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 540,
        y: 340,
        name: "Stora mossen",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 580,
        y: 340,
        name: "ALVIK",
        position: LABEL_POSITION.TOP,
      },
      {
        x: 620,
        y: 340,
        name: "Kristineberg",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 650,
        y: 340,
        name: "Thorildsplan",
        position: LABEL_POSITION.BOTTOM_LEFT,
      },
      {
        x: 680,
        y: 340,
        name: "Fridhemsplan",
        multi: true,
        position: LABEL_POSITION.TOP_RIGHT,
      },
      {
        x: 720,
        y: 340,
        name: "St Eriksplan",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 760, y: 340, name: "Odenplan", position: LABEL_POSITION.TOP_RIGHT },
      {
        x: 800,
        y: 340,
        name: "Rådmansgatan",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 840, y: 340, name: "Hötorget", position: LABEL_POSITION.TOP_RIGHT },
      { x: 930, y: 380, name: "T-CENTRALEN", multi: true },
      { x: 930, y: 420, name: "Gamla stan", multi: true },
      { x: 930, y: 460, name: "Slussen", multi: true },
      { x: 930, y: 490, name: "Skanstull" },
      { x: 930, y: 520, name: "Gullmarsplan" },
      { x: 840, y: 605, name: "Globen" },
      { x: 800, y: 640, name: "Enskede\n gård" },
      { x: 760, y: 680, name: "Sockenplan" },
      { x: 720, y: 720, name: "Svedmyra" },
      { x: 680, y: 760, name: "Stureby" },
      { x: 640, y: 800, name: "Bandhagen" },
      { x: 600, y: 840, name: "Högdalen" },
      { x: 560, y: 880, name: "Rågsved" },
      { x: 490, y: 950, name: "HAGSÄTRA", end: true },
    ],
  },
  {
    color: "#E61D26",
    line: 13,
    points: [
      { x: 100, y: 950, name: "NORSBORG", start: true },
      { x: 140, y: 900, name: "Hallunda" },
      { x: 170, y: 860, name: "Alby" },
      { x: 200, y: 820, name: "Fittja" },
      { x: 230, y: 780, name: "Masmo" },
      { x: 260, y: 740, name: "Vårby gård" },
      { x: 290, y: 700, name: "Vårberg" },
      { x: 320, y: 660, name: "Skärholmen" },
      { x: 350, y: 620, name: "Sätra" },
      { x: 380, y: 580, name: "Bredäng" },
      { x: 410, y: 540, name: "Mälarhöjden" },
      { x: 440, y: 500, name: "Axelsberg", position: LABEL_POSITION.TOP_RIGHT },
      { x: 500, y: 500, name: "Örnsberg", position: LABEL_POSITION.TOP_RIGHT },
      { x: 560, y: 500, name: "Aspudden", position: LABEL_POSITION.TOP_RIGHT },
      {
        x: 620,
        y: 500,
        name: "Liljeholmen",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 680, y: 500, name: "Hornstull", position: LABEL_POSITION.TOP_RIGHT },
      {
        x: 740,
        y: 500,
        name: "Zinkensdamm",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      {
        x: 800,
        y: 500,
        name: "Mariatorget",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 930, y: 460, name: "Slussen", multi: true },
      { x: 930, y: 420, name: "Gamla stan", multi: true },
      { x: 930, y: 380, name: "T-CENTRALEN", multi: true },
      { x: 930, y: 320, name: "Östermalmstorg" },
      { x: 980, y: 280, name: "Karlaplan" },
      { x: 1030, y: 240, name: "Gärdet" },
      { x: 1080, y: 200, name: "ROPSTEN", end: true },
    ],
  },
  {
    color: "#E61D26",
    line: 14,
    points: [
      { x: 470, y: 700, name: "FRUÄNGEN", start: true },
      { x: 500, y: 660, name: "Västertorp" },
      { x: 530, y: 620, name: "Hägerstensåsen" },
      { x: 560, y: 580, name: "Telefonplan" },
      { x: 590, y: 540, name: "Midsommarkransen" },
      {
        x: 620,
        y: 500,
        name: "Liljeholmen",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 680, y: 500, name: "Hornstull", position: LABEL_POSITION.TOP_RIGHT },
      {
        x: 740,
        y: 500,
        name: "Zinkensdamm",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      {
        x: 800,
        y: 500,
        name: "Mariatorget",
        position: LABEL_POSITION.TOP_RIGHT,
      },
      { x: 930, y: 460, name: "Slussen", multi: true },
      { x: 930, y: 420, name: "Gamla stan", multi: true },
      { x: 930, y: 380, name: "T-CENTRALEN", multi: true },
      { x: 930, y: 320, name: "Östermalmstorg" },
      { x: 930, y: 220, name: "Stadion" },
      { x: 930, y: 160, name: "Tekniska högskolan" },
      { x: 930, y: 120, name: "Universitetet" },
      { x: 930, y: 85, name: "Bergshamra" },
      { x: 930, y: 50, name: "Danderyds sjukhus" },
      { x: 930, y: 20, name: "MÖRBY CENTRUM", end: true },
    ],
  },
];

export default metroLineData;
